version: '3'
services:
  diecastcollectiontracker-mongo:
    image: mongo:4.4.18
    container_name: diecastcollectiontracker-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  diecastcollectiontracker-backend:
    build: ./backend
    image: wwwescape/diecastcollectiontracker-backend:latest
    container_name: diecastcollectiontracker-backend
    environment:
      - MONGO_URI=mongodb://diecastcollectiontracker-mongo:27017/diecastcollectiontracker
      - PORT=2105
    volumes:
      - uploads:/app/uploads
    depends_on:
      - diecastcollectiontracker-mongo
  diecastcollectiontracker-frontend:
    build: ./frontend
    image: wwwescape/diecastcollectiontracker-frontend:latest
    container_name: diecastcollectiontracker-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=1602
      - REACT_APP_API_URL=
    depends_on:
      - diecastcollectiontracker-backend
  diecastcollectiontracker-nginx:
    image: nginx:latest
    container_name: diecastcollectiontracker-nginx
    ports:
      - "1602:1602"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - uploads:/app/uploads
    depends_on:
      - diecastcollectiontracker-backend
      - diecastcollectiontracker-frontend
volumes:
  mongo-data:
  uploads: