"""create car domain tables

Revision ID: a406c09729b9
Revises: d10e76d8b2de
Create Date: 2026-06-30 22:35:53.527335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a406c09729b9'
down_revision: Union[str, None] = 'd10e76d8b2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors')),
    sa.UniqueConstraint('name', name=op.f('uq_colors_name'))
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers')),
    sa.UniqueConstraint('name', name=op.f('uq_manufacturers_name'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True, comment='hex color for UI chips'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_types')),
    sa.UniqueConstraint('name', name=op.f('uq_vehicle_types_name'))
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_series_manufacturer_id_manufacturers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('manufacturer_id', 'name', name='uq_series_manufacturer_id_name')
    )
    op.create_index(op.f('ix_series_manufacturer_id'), 'series', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_series_name'), 'series', ['name'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cast_number', sa.String(length=100), nullable=True),
    sa.Column('collection_number', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('owned', 'wishlist', name='carstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_cars_color_id_colors')),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_cars_manufacturer_id_manufacturers')),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_cars_series_id_series')),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], name=op.f('fk_cars_vehicle_type_id_vehicle_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cars'))
    )
    op.create_index(op.f('ix_cars_color_id'), 'cars', ['color_id'], unique=False)
    op.create_index(op.f('ix_cars_manufacturer_id'), 'cars', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_cars_name'), 'cars', ['name'], unique=False)
    op.create_index(op.f('ix_cars_series_id'), 'cars', ['series_id'], unique=False)
    op.create_index(op.f('ix_cars_vehicle_type_id'), 'cars', ['vehicle_type_id'], unique=False)
    op.create_table('car_tags',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name=op.f('fk_car_tags_car_id_cars')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_car_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('car_id', 'tag_id', name=op.f('pk_car_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_tags')
    op.drop_index(op.f('ix_cars_vehicle_type_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_series_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_name'), table_name='cars')
    op.drop_index(op.f('ix_cars_manufacturer_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_color_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_series_name'), table_name='series')
    op.drop_index(op.f('ix_series_manufacturer_id'), table_name='series')
    op.drop_table('series')
    op.drop_table('vehicle_types')
    op.drop_table('tags')
    op.drop_table('manufacturers')
    op.drop_table('colors')
    # ### end Alembic commands ###
